//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PAQUETE
    {
        public decimal servicioID { get; set; }
        public decimal paqueteID { get; set; }
        public decimal id { get; set; }
    
        public virtual SERVICIOS SERVICIOS { get; set; }
        public virtual SERVICIOS SERVICIOS1 { get; set; }
    }
}
