//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA_SERVICIO
    {
        public decimal id { get; set; }
        public Nullable<decimal> facturaID { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<double> isv { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual FACTURA_SERVICIO FACTURA_SERVICIO { get; set; }
    }
}
