//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA_SERVICIO
    {
        public decimal id { get; set; }
        public Nullable<decimal> facturaID { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<double> isv { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<decimal> servicioID { get; set; }
    
        public virtual FACTURA_SERVICIO FACTURA_SERVICIO { get; set; }
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
