//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CONTRATO
    {
        public Nullable<decimal> contratoID { get; set; }
        public Nullable<decimal> servicioID { get; set; }
        public decimal id { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> realizado { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
