//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPONIBILIDAD_TECNICOS
    {
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> tecnicoID { get; set; }
        public decimal id { get; set; }
    
        public virtual TECNICOS TECNICOS { get; set; }
    }
}
