//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA_SERVICIO()
        {
            this.DETALLE_FACTURA_SERVICIO = new HashSet<DETALLE_FACTURA_SERVICIO>();
        }
    
        public decimal id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public decimal servicioID { get; set; }
        public decimal clienteID { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> ordenID { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_FACTURA_SERVICIO> DETALLE_FACTURA_SERVICIO { get; set; }
        public virtual ORDEN_TRABAJO ORDEN_TRABAJO { get; set; }
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
