//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewClientesActivos
    {
        public decimal id { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
        public string RTN { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
    }
}
